name: Make NDK (Bionic libc) for aarch64
run-name: Make NDK-r${{inputs.version}}${{inputs.revision}} bionic for aarch64
on:
  workflow_dispatch:
    inputs:
      version:
        description: "NDK Release version:"
        default: '30'
        required: true
        type: string
      revision:
        description: "NDK Release revision:"
        default: '-beta1'
        required: false
        type: string

jobs:
  make:
    name: Make NDK Bionic for aarch64
    runs-on: ubuntu-24.04
    env:
      ROOTDIR: ${{github.workspace}}
      # 目标架构固定为 aarch64-linux-android
      TARGET: aarch64-linux-android
      # aarch64 对应的 Android 平台级别
      ANDROID_PLATFORM: 25
      # 为缓存创建一个专门的工作目录
      WORK_DIR: ${{ runner.temp }}/workdir

    steps:
      - name: Checkout android-ndk-custom
        uses: actions/checkout@v5
        with:
          path: ${{github.workspace}}

      # 步骤 1: 缓存依赖项以加速后续运行
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ${{ env.WORK_DIR }}
          key: ${{ runner.os }}-${{ env.TARGET }}-${{ hashFiles('**/sources/**', '**/patches/**') }}

      - name: Get Official NDK
        run: |
          echo "Downloading NDK r${{inputs.version}}${{inputs.revision}}..."
          curl -sSfL -o android-ndk.zip "https://dl.google.com/android/repository/android-ndk-r${{inputs.version}}${{inputs.revision}}-linux.zip"
          unzip -qq android-ndk.zip -d ${{ runner.temp }}

      - name: Install Dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt install -y ninja-build python3.11

      - name: Build Extra Dependencies
        run: |
          mkdir -p ${{ env.WORK_DIR }}
          cd ${{ env.WORK_DIR }}

          HAVE_PSELECT=yes

          NDK_DIR="${{ runner.temp }}/android-ndk-r${{inputs.version}}${{inputs.revision}}"
          TOOLCHAIN=$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64
          SHADER_TOOLS_BIN="$NDK_DIR/shader-tools/linux-x86_64"
          PREBUILT_BIN="$NDK_DIR/prebuilt/linux-x86_64/bin"
          MAKE_VERSION=4.4
          YASM_VERSION=$($PREBUILT_BIN/yasm --version | sed -n '1s/.*yasm \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
          
          if [ "${{inputs.version}}" -ge 30 ]; then
            GLSLC_VERSION_OUTPUT="$($SHADER_TOOLS_BIN/glslc --version)"
            SHADERC_HASH=$(echo "$GLSLC_VERSION_OUTPUT" | sed -n 's/^shaderc .* \([a-f0-9]\{40\}\)$/\1/p')
            SPIRV_TOOLS_HASH=$(echo "$GLSLC_VERSION_OUTPUT" | sed -n 's/^spirv-tools .* \([a-f0-9]\{40\}\)$/\1/p')
            GLSLANG_HASH=$(echo "$GLSLC_VERSION_OUTPUT" | sed -n 's/^glslang \([0-9a-f]\{40\}\)$/\1/p')
            SPIRV_HEADERS_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-tools/+/${SPIRV_TOOLS_HASH}/DEPS?format=TEXT" | base64 -d | grep -oP "'spirv_headers_revision': '\K[a-f0-9]{40}")
          else
            NDK_TAG=$($SHADER_TOOLS_BIN/glslc --version | sed -n 's/.*\(ndk-[^ ]*\).*/\1/p' | sed 's/+/%2B/g' | head -n 1)
            SHADERC_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/shaderc/+/refs/tags/${NDK_TAG}" | grep -oP 'href="/platform/external/shaderc/shaderc/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/shaderc\/\+archive\///' | sed 's/\.tar\.gz"$//')
            SPIRV_TOOLS_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-tools/+/refs/tags/${NDK_TAG}" | grep -oP 'href="/platform/external/shaderc/spirv-tools/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/spirv-tools\/\+archive\///' | sed 's/\.tar\.gz"$//')
            SPIRV_HEADERS_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-headers/+/refs/tags/${NDK_TAG}" | grep -oP 'href="/platform/external/shaderc/spirv-headers/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/spirv-headers\/\+archive\///' | sed 's/\.tar\.gz"$//')
            GLSLANG_HASH=$(curl -LkSs "https://android.googlesource.com/platform/external/shaderc/glslang/+/refs/tags/${NDK_TAG}" | grep -oP 'href="/platform/external/shaderc/glslang/\+archive/[a-f0-9]{40}\.tar\.gz"' | sed -E 's/^href="\/platform\/external\/shaderc\/glslang\/\+archive\///' | sed 's/\.tar\.gz"$//')
          fi

          # GNU Make
          if [ ! -d "make" ]; then
            cat $ROOTDIR/sources/make-$MAKE_VERSION.tar.gz | gzip -d | tar -x
            mv make-$MAKE_VERSION make
            cd make
            cp ${{github.workspace}}/config/config.sub build-aux
            cp ${{github.workspace}}/config/config.guess build-aux
            ./configure \
            --prefix="${PWD}/build" \
            --build=x86_64-linux-gnu \
            --host=${{ env.TARGET }} \
            --disable-posix-spawn \
            CC=${TOOLCHAIN}/bin/${{env.TARGET}}${ANDROID_PLATFORM}-clang \
            CXX=${TOOLCHAIN}/bin/${{env.TARGET}}${ANDROID_PLATFORM}-clang++ \
            CFLAGS="-Wno-error=implicit-function-declaration -static" \
            LDFLAGS="-static" \
            ac_cv_lib_elf_elf_begin=no \
            am_cv_func_iconv=no \
            ac_cv_func_pselect=$HAVE_PSELECT
            make -j"$(nproc --all)" install
            cd ..
          fi
          
          # YASM
          if [ ! -d "yasm" ]; then
            cat $ROOTDIR/sources/yasm-$YASM_VERSION.tar.gz | gzip -d | tar -x
            mv yasm-$YASM_VERSION yasm
            cd yasm
            cp $ROOTDIR/config/config.sub config
            cp $ROOTDIR/config/config.guess config
            ./configure \
            --prefix="${PWD}/build" \
            --build=x86_64-linux-gnu \
            --host=${{ env.TARGET }} \
            --disable-nls \
            CC=${TOOLCHAIN}/bin/${{env.TARGET}}${ANDROID_PLATFORM}-clang \
            CFLAGS="-static"
            make -j"$(nproc --all)" install
            cd ..
          fi

          # SPIRV-Tools and shaderc
          if [ ! -d "shaderc" ]; then
            mkdir -p shaderc
            cd shaderc
            curl -LkSs "https://android.googlesource.com/platform/external/shaderc/shaderc/+archive/$SHADERC_HASH.tar.gz" | tar -xz
            mkdir -p third_party/spirv-tools/external/spirv-headers
            curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-tools/+archive/$SPIRV_TOOLS_HASH.tar.gz" | tar -xz -C third_party/spirv-tools
            curl -LkSs "https://android.googlesource.com/platform/external/shaderc/spirv-headers/+archive/$SPIRV_HEADERS_HASH.tar.gz" | tar -xz -C third_party/spirv-tools/external/spirv-headers
            mkdir -p third_party/glslang
            curl -LkSs "https://android.googlesource.com/platform/external/shaderc/glslang/+archive/$GLSLANG_HASH.tar.gz" | tar -xz -C third_party/glslang
            
            cd third_party/glslang
            sed -i '/^elseif(UNIX)$/,/^[[:space:]]*endif()$/d' StandAlone/CMakeLists.txt
            cd ../spirv-tools
            git init --quiet && git apply $ROOTDIR/patches/ndk/spirv/full_static.patch && rm -rf .git
            cd ../..
            git init --quiet && git apply $ROOTDIR/patch
